#!/usr/bin/env bash


# ==========
# dotbot: dotfile bootstrapper
# ==========
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# ==========
# Linux program installs with apt
# ==========
sudo apt -y install git

read -r -p "What is your github.com username? " githubuser
read -r -p "What is your first name? " firstname
read -r -p "What is your last name? " lastname

fullname="$firstname $lastname"

read -r -p "What is your email? " email

running "replacing items in .gitconfig with your info ($fullname, $email, $githubuser)"
sed -i 's/GITHUBEMAIL/'$email'/' $HOME/.gitconfig;
sed -i 's/GITHUBUSER/'$githubuser'/' $HOME/.gitconfig;


sudo apt -y install curl nodejs npm tmux zsh

chsh -s $(which zsh)
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

curl -sL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | sh
