#!/usr/bin/env bash

# ==========
# Linux program installs with apt
# ==========
sudo apt -y install software-properties-common curl ffmpeg nodejs npm tmux xclip zsh python3-setuptools xdotool python3-gi libinput-tools python-gobject wmctrl

snap install spotify caprine
snap install slack --classic

wget https://github.com/Eugeny/terminus/releases/download/v1.0.73/terminus-1.0.73-linux.deb
sudo dpkg -i terminus-1.0.73-linux.deb
sudo apt --fix-broken install
rm terminus-1.0.73-linux.snap


chsh -s $(which zsh)

# ==========
# Manual installs
# ==========

mkdir $HOME/bin

# libinput-gestures config
sudo gpasswd -a $USER input

# Mouse Gestures
mkdir $HOME/bin/gestures
git clone https://github.com/bulletmark/libinput-gestures.git $HOME/bin/gestures
cd $HOME/bin/gestures
sudo make install

libinput-gestures-setup autostart
libinput-gestures-setup start

sudo add-apt-repository ppa:daniruiz/flat-remix
sudo apt-get update
sudo apt-get install flat-remix-gnome flat-remix

echo "Installing Google Chrome..."
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb

echo "Installing Google Drive ocamlfuse..."
sudo add-apt-repository -y ppa:alessandro-strada/ppa
sudo apt update && sudo apt install google-drive-ocamlfuse
mkdir ~/googledrive
google-drive-ocamlfuse ~/googledrive

echo "Installing Dropbox..."
wget "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.01.31_amd64.deb"
sudo dpkg -i "download?dl=packages%2Fubuntu%2Fdropbox_2019.01.31_amd64.deb"
rm "download?dl=packages%2Fubuntu%2Fdropbox_2019.01.31_amd64.deb"

echo "Installing Mendeley..."
get "https://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.19.3-linux-x86_64.tar.bz2"
tar -zxvf mendeleydesktop-1.19.3-linux-x86_64.tar.bz2 $HOME/bin/mendeley
export PATH="$HOME/bin/mendeley/bin/:$PATH"

echo "Installing tpm..."
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "Installing Zplug..."
wget -O installer.sh https://raw.githubusercontent.com/zplug/installer/master/installer.zsh
zsh installer.sh
rm installer.sh

echo "Installing miniconda..."
wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash miniconda.sh
rm miniconda.sh

echo "Installing basic_pkgs.txt..."
conda install -f basic_pkgs.txt

# ==========
# dotbot: dotfile bootstrapper
# ==========
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

